modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Kaden-S/ClayConversion/issues" 
[[mods]] 
  modId="clayconversion"
  version="${file.jarVersion}"
  displayName="Clay Conversion"
  updateJSONURL="https://raw.githubusercontent.com/Kaden-S/ClayConversion/Files/update.json"
  displayURL="https://minecraft.curseforge.com/projects/clay-conversion"
  logoFile="clayball.png"
  authors="Kaden Sharpin"
  displayTest="MATCH_VERSION"
  description='Convert your clay blocks into clay balls easily with this mod!'

[[dependencies.clayconversion]] 
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.clayconversion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
