modLoader="javafml" 
loaderVersion="[39,)" 
license="All rights reserved"
issueTrackerURL="https://github.com/KadenS2005/Clay-Conversion/issues" 
[[mods]] 
  modId="clayconversion"
  version="1.5" 
  displayName="Clay Conversion"
  updateJSONURL="https://raw.githubusercontent.com/KadenS2005/ClayConversion/Files/update.json"
  displayURL="https://minecraft.curseforge.com/projects/clay-conversion"
  logoFile="clayball.png"
  authors="Kaden Sharpin"
  description='Convert your clay blocks into clay balls easily with this mod!'
  
[[dependencies.examplemod]] 
    modId="forge" 
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
